/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GlitterMaterial } from '../glitterMaterial'

const customUniforms = {
  uGlitterSize: { value: 350.0 },
  uGlitterDensity: { value: 0.1 }
}

const debugObject = {
  glitterColor: '#bb05bb'
}

export function Suzanne ({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/gltf/Suzanne.glb', true)

  const glitterMaterial = new GlitterMaterial(customUniforms, {
    color: debugObject.glitterColor
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Suzanne.geometry} material={glitterMaterial} />
    </group>
  )
}

useGLTF.preload('/gltf/Suzanne.glb')
